name: PR Validation

on:
  pull_request:
    branches: [main, main-candidate]
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    uses: YCITC/reuse-workflow-test/.github/workflows/pr-validation.yml@main
    with:
      config-path: .github/labeler.yml